# Test configuration generated by CMake

SLIM_BINARY = "/home/ueda/slim-cmake/src/slim"
LMNTAL_HOME = "/home/ueda/LMNtal/lmntal-compiler"
BUILD_TYPE = "Release"
SOURCE_DIR = "/home/ueda/slim-cmake"
BINARY_DIR = "/home/ueda/slim-cmake"

# Test timeouts (seconds)
TEST_TIMEOUTS = {
    "system": 30,
    "library": 45,
    "statespace": 300,
    "benchmark": 600
}

# Parallel execution limits
MAX_PARALLEL_TESTS = {
    "system": 8,
    "library": 4,
    "statespace": 1,  # Model checking is resource intensive
    "benchmark": 1
}

# Test result directories
RESULTS_DIR = "/home/ueda/slim-cmake/test_results"
BENCHMARK_DIR = "/home/ueda/slim-cmake/benchmarks"
COVERAGE_DIR = "/home/ueda/slim-cmake/coverage"
