
./src/slim --nd --ltl --nc benchmarkset/abp0.nc --psym benchmarkset/abp0.psym  benchmarkset/abp.lmn 
./src/slim --nd --ltl --nc benchmarkset/abp1.nc --psym benchmarkset/abp1.psym  benchmarkset/abp.lmn 
./src/slim --nd --ltl --nc benchmarkset/bakery0.nc --psym benchmarkset/bakery0.psym  benchmarkset/bakery.lmn 
./src/slim --nd --ltl --nc benchmarkset/bakery1.nc --psym benchmarkset/bakery1.psym  benchmarkset/bakery.lmn 
./src/slim --nd --ltl --nc benchmarkset/bubble0.nc --psym benchmarkset/bubble0.psym  benchmarkset/bubble.lmn 
./src/slim --nd --ltl --nc benchmarkset/byzantine0.nc --psym benchmarkset/byzantine0.psym  benchmarkset/byzantine.lmn 
./src/slim --nd --ltl --nc benchmarkset/edfs0.nc --psym benchmarkset/edfs0.psym  benchmarkset/edfs.lmn 
./src/slim --nd --ltl --nc benchmarkset/edfs1.nc --psym benchmarkset/edfs1.psym  benchmarkset/edfs.lmn 
./src/slim --nd --ltl --nc benchmarkset/elevator0.nc --psym benchmarkset/elevator0.psym  benchmarkset/elevator.lmn 
./src/slim --nd --ltl --nc benchmarkset/elevator1.nc --psym benchmarkset/elevator1.psym  benchmarkset/elevator.lmn 
./src/slim --nd --ltl --nc benchmarkset/firewire0.nc --psym benchmarkset/firewire0.psym  benchmarkset/firewire.lmn 
./src/slim --nd --ltl --nc benchmarkset/firewire1.nc --psym benchmarkset/firewire1.psym  benchmarkset/firewire.lmn 
./src/slim --nd --ltl --nc benchmarkset/firewire2.nc --psym benchmarkset/firewire2.psym  benchmarkset/firewire.lmn 
./src/slim --nd --ltl --nc benchmarkset/josephus0.nc --psym benchmarkset/josephus0.psym  benchmarkset/josephus.lmn 
./src/slim --nd --ltl --nc benchmarkset/jsp0.nc --psym benchmarkset/jsp0.psym  benchmarkset/jsp.lmn 
./src/slim --nd --ltl --nc benchmarkset/knight0.nc --psym benchmarkset/knight0.psym  benchmarkset/knight.lmn 
./src/slim --nd --ltl --nc benchmarkset/lambda0.nc --psym benchmarkset/lambda0.psym  benchmarkset/lambda.lmn 
./src/slim --nd --ltl --nc benchmarkset/lbully0.nc --psym benchmarkset/lbully0.psym  benchmarkset/lbully.lmn 
./src/slim --nd --ltl --nc benchmarkset/lring0.nc --psym benchmarkset/lring0.psym  benchmarkset/lring.lmn 
./src/slim --nd --ltl --nc benchmarkset/mutex0.nc --psym benchmarkset/mutex0.psym  benchmarkset/mutex.lmn 
./src/slim --nd --ltl --nc benchmarkset/mutex1.nc --psym benchmarkset/mutex1.psym  benchmarkset/mutex.lmn 
./src/slim --nd --ltl --nc benchmarkset/mutex2.nc --psym benchmarkset/mutex2.psym  benchmarkset/mutex.lmn 
./src/slim --nd --ltl --nc benchmarkset/peterson0.nc --psym benchmarkset/peterson0.psym  benchmarkset/peterson.lmn 
./src/slim --nd --ltl --nc benchmarkset/peterson1.nc --psym benchmarkset/peterson1.psym  benchmarkset/peterson.lmn 
./src/slim --nd --ltl --nc benchmarkset/phi0.nc --psym benchmarkset/phi0.psym  benchmarkset/phi.lmn 
./src/slim --nd --ltl --nc benchmarkset/phiM0.nc --psym benchmarkset/phiM0.psym  benchmarkset/phiM.lmn 
./src/slim --nd --ltl --nc benchmarkset/qlock0.nc --psym benchmarkset/qlock0.psym  benchmarkset/qlock.lmn 
./src/slim --nd --ltl --nc benchmarkset/qlock1.nc --psym benchmarkset/qlock1.psym  benchmarkset/qlock.lmn 
./src/slim --nd --ltl --nc benchmarkset/qlock2.nc --psym benchmarkset/qlock2.psym  benchmarkset/qlock.lmn 
./src/slim --nd --ltl --nc benchmarkset/queen0.nc --psym benchmarkset/queen0.psym  benchmarkset/queen.lmn 
./src/slim --nd --ltl --nc benchmarkset/rabbit0.nc --psym benchmarkset/rabbit0.psym  benchmarkset/rabbit.lmn 
./src/slim --nd --ltl --nc benchmarkset/rms0.nc --psym benchmarkset/rms0.psym  benchmarkset/rms.lmn 
./src/slim --nd --ltl --nc benchmarkset/sstd0.nc --psym benchmarkset/sstd0.psym  benchmarkset/sstd.lmn 
./src/slim --nd --ltl --nc benchmarkset/swp0.nc --psym benchmarkset/swp0.psym  benchmarkset/swp.lmn 
./src/slim --nd --ltl --nc benchmarkset/swp_simple0.nc --psym benchmarkset/swp_simple0.psym  benchmarkset/swp_simple.lmn 
