#!/bin/sh
./check.pl \
	/testsuite/miscellaneous/case1 \
	/testsuite/miscellaneous/case2 \
	/testsuite/miscellaneous/case3 \
	/testsuite/miscellaneous/case4 \
	/testsuite/miscellaneous/case5 \
	/testsuite/miscellaneous/case6 \
	/testsuite/miscellaneous/case7 \
	/testsuite/miscellaneous/case8 \
	/testsuite/miscellaneous/case9 \
	/testsuite/miscellaneous/case10 \
	/testsuite/miscellaneous/case11 \
	/testsuite/miscellaneous/case12 \
	/testsuite/miscellaneous/case13 \
	/testsuite/miscellaneous/case14 \
	/testsuite/miscellaneous/case15 \
	/testsuite/miscellaneous/case16 \
	/testsuite/miscellaneous/case17 \
	/testsuite/miscellaneous/case18 \
	/testsuite/miscellaneous/case19 \
	/testsuite/miscellaneous/case20 \
