#!/bin/sh
./check.pl \
	/testsuite/guard_ground/case1 \
	/testsuite/guard_ground/case2 \
	/testsuite/guard_ground/case3 \
	/testsuite/guard_ground/case4 \
	/testsuite/guard_ground/case5 \
	/testsuite/guard_ground/case6 \
	/testsuite/guard_ground/case7 \
	/testsuite/guard_ground/case8 \
	/testsuite/guard_ground/case9 \
	/testsuite/guard_ground/case10 \
	/testsuite/guard_ground/case11 \
	/testsuite/guard_ground/case12 \
	/testsuite/guard_ground/case13 \
	/testsuite/guard_ground/case14 \
	/testsuite/guard_ground/case15 \
	/testsuite/guard_ground/case16 \
	/testsuite/guard_ground/case17 \
	/testsuite/guard_ground/case18 \
	/testsuite/guard_ground/case19 \
	/testsuite/guard_ground/case20 \
	/testsuite/guard_ground/case21 \
	/testsuite/guard_ground/case22 \
	/testsuite/guard_ground/case23 \
	/testsuite/guard_ground/case24 \
	/testsuite/guard_ground/case25 \
	/testsuite/guard_ground/case26 \
	/testsuite/guard_ground/case27 \
	/testsuite/guard_ground/case28 \
	/testsuite/guard_ground/case29 \
	/testsuite/guard_ground/case30 \
	/testsuite/guard_ground/case31