#!/bin/sh
./check.pl \
	/testsuite/guard_int/case1 \
	/testsuite/guard_int/case2 \
	/testsuite/guard_int/case3 \
	/testsuite/guard_int/case4 \
	/testsuite/guard_int/case5 \
	/testsuite/guard_int/case6 \
	/testsuite/guard_int/case7 \
	/testsuite/guard_int/case8 \
	/testsuite/guard_int/case9 \
	/testsuite/guard_int/case10 \
	/testsuite/guard_int/case11 \
	/testsuite/guard_int/case12 \
	/testsuite/guard_int/case13 \
	/testsuite/guard_int/case14 \
	/testsuite/guard_int/case15 \
	/testsuite/guard_int/case16 \
	/testsuite/guard_int/case17 \
	/testsuite/guard_int/case18 \
	/testsuite/guard_int/case19 \
	/testsuite/guard_int/case20 \
	/testsuite/guard_int/case21 \
	/testsuite/guard_int/case22 \
