#!/usr/bin/perl
######################################
#                                    #
# Java LMNtal system checker on Perl #
#                                    #
######################################
# AUTHOR : kudo
# LAST UPDATE : 2006/05/22

# This is LMNtal system checker.

use Cwd;
use File::Basename;
$pwd = Cwd::getcwd();

$lmntal_runtime = $ARGV[0] || $ENV{SLIM_BINARY} || "/home/ueda/slim/build/src/slim";  # First argument is the slim binary path
$lmntal_home = $ENV{LMNTAL_HOME};
$count = 1;
$test_failed = 0;
$options = $ENV{slim_CHECK_OPTIONS};

# Generate .il files on demand using create_testdata.awk to transform .lmntest files
sub generate_il_file {
    my ($il_file) = @_;
    my $lmntest_file = $il_file;
    $lmntest_file =~ s/\.il$/.lmntest/;
    
    if (-f $lmntest_file && !(-f $il_file || -M $il_file > -M $lmntest_file)) {
        # Use create_testdata.awk to transform .lmntest file into proper LMNtal test program
        my $script_dir = dirname(__FILE__);
        my $awk_script = "$script_dir/create_testdata.awk";
        
        # Create temporary .lmn file using AWK transformation
        my $temp_lmn = $il_file;
        $temp_lmn =~ s/\.il$/.lmn/;
        
        my $awk_cmd = "awk -f '$awk_script' '$lmntest_file' > '$temp_lmn'";
        system($awk_cmd);
        
        # Compile to .il using LMNtal compiler
        my $lmntal_cmd = "java -cp '$lmntal_home/bin/lmntal.jar' runtime.FrontEnd --slimcode '$temp_lmn' > '$il_file'";
        system($lmntal_cmd);
        
        # Clean up temporary .lmn file
        unlink($temp_lmn);
    }
}

print $count . ".." . ($#ARGV) . "\n";  # Subtract 1 since first arg is binary path
for my $i (1..$#ARGV) {
	$filename = $ARGV[$i];
	
	# Generate .il file if it doesn't exist
	generate_il_file($filename);
	
	# Extract .lmntest filename from .il path to get expected output
	$lmntest_file = $filename;
	$lmntest_file =~ s/\.il$/.lmntest/;
	
	my $expected_output = "";
	my $computed_result = "";
	
	if (-f $lmntest_file) {
		open (FILE, "< " . $lmntest_file);
		@file = <FILE>;
		$expected_output = $file[1];                           # Line 2 is expected output
		$expected_output =~ s/\n//;                            # Remove newline
		close (FILE);
	} else {
		$expected_output = "expected output";
	}
	
	# For verbose mode, also run the original computation to see actual result
	if ($ENV{VERBOSE} || $ENV{V}) {
		# Generate .il file with just the original program (not create_testdata.awk)
		my $orig_il_file = $filename;
		$orig_il_file =~ s/\.il$/_orig.il/;
		
		if (-f $lmntest_file) {
			# Extract first line (original LMNtal program) from .lmntest file
			open(my $test_fh, '<', $lmntest_file) or die "Cannot read $lmntest_file: $!";
			my $lmntal_program = <$test_fh>;
			close($test_fh);
			chomp($lmntal_program);
			
			# Create temporary .lmn file with just the LMNtal program
			my $temp_lmn = $orig_il_file;
			$temp_lmn =~ s/\.il$/.lmn/;
			
			open(my $lmn_fh, '>', $temp_lmn) or die "Cannot create $temp_lmn: $!";
			print $lmn_fh $lmntal_program . "\n";
			close($lmn_fh);
			
			# Compile to .il using LMNtal compiler
			my $lmntal_cmd = "java -cp '$lmntal_home/bin/lmntal.jar' runtime.FrontEnd --slimcode '$temp_lmn' > '$orig_il_file'";
			system($lmntal_cmd);
			
			# Run original computation to get actual result
			my $orig_run = $lmntal_runtime . " --hide-ruleset " . $options ." ". $orig_il_file;
			$computed_result = `$orig_run 2>&1`;
			$computed_result =~ s/\n//;
			$computed_result =~ s/\s*\.\s*$//;  # Remove trailing dot and whitespace
			
			# Clean up temporary files
			unlink($temp_lmn);
			unlink($orig_il_file);
		}
	}
	
	# Run the equivalence check (create_testdata.awk version)
	$check_run = $lmntal_runtime . " --hide-ruleset " . $options ." ". $filename;
	$checked = `$check_run 2>&1`;
	my $exit_code = $? >> 8;
	
	# Clean up the actual output for display
	my $display_output = $checked;
	$display_output =~ s/\n//;
	
	# Check for segmentation fault or other runtime crashes
	if ($exit_code != 0 || ($checked eq "" && $expected_output ne "")) {
		print "not ok " . $count;
		if ($exit_code != 0) {
			print " - SLIM crashed with exit code $exit_code";
		} else {
			print " - SLIM produced no output (possible segfault)";
		}
		print "\n";
		$test_failed = 1;
		$count = $count + 1;
		next;
	}
	
	# Check if output starts with "ok" (generated by create_testdata.awk when test passes)
	$result = index ($checked, "ok");

	if ($result == 0) {
		print "ok " . $count;
		# Verbose logging: show what was computed vs expected even for passing tests
		if ($ENV{VERBOSE} || $ENV{V}) {
			print " - computed '$computed_result' matches expected '$expected_output'";
		}
	} else {
		print "not ok " . $count;
		print " - '" . $display_output . "' should be '" . $expected_output . "'";
	}
	print "\n";
	$count = $count + 1;
}

exit($test_failed ? 1 : 0);
