
  name: lmntal-slim
  version: git # just for humans, typically '1.2+git' or '1.3.2'
  summary: SLIM - Slim LMNtal Imprementation # 79 char long summary
  description: |
    SLIM is the de-facto standard runtime of 
    a hierarchical graph rewriting language, LMNtal,
    and also has powerful features of model checkers.

  base: core18

  grade: stable # must be 'stable' to release into candidate/stable channels
  confinement: strict # use 'strict' once you have the right plugs and slots

  architectures: [amd64]

  parts:
    lmntal-slim:
      # See 'snapcraft plugins'
      plugin: autotools
      # install-via: prefix
      source: .
      configflags: ["--datadir=/snap/$SNAPCRAFT_PROJECT_NAME/current/share"]
      organize:
        snap/$SNAPCRAFT_PROJECT_NAME/current/share: share
      build-environment:
        - LMNTAL_HOME: /snap/lmntal-compiler/current/lib/lmntal-compiler
      build-snaps:
        - lmntal-compiler
      build-packages:
        - g++
        - make
        - automake
        - autoconf
        - flex
        - bison
        - ruby
        - libtool
        - re2c
        - openjdk-8-jre
      stage-packages:
        - libgomp1
  
  apps:
    lmntal-slim:
      command: slim
      plugs: [home]
